name: Agregar comentarios a main.py y pushear a la rama diego

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  agregar_comentarios:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Ejecutar script para agregar comentarios
      run: |
        python3 script.py

    - name: Configurar nombre y correo para Git
      run: |
        git config --global user.name "AlexanderSanchezGarcia"
        git config --global user.email "alexander.sanchez.gm@gmail.com"

    - name: Crear nueva rama diego si no existe
      run: |
        git checkout -b diego || git checkout diego

    - name: Obtener cambios remotos en la rama diego
      run: |
        git pull origin diego --rebase  # Obtener los últimos cambios remotos y rebasear

    - name: Commitear los cambios
      run: |
        git add .
        git commit -m "Agregar comentarios a main.py" || echo "No hay cambios para commitear"

    - name: Pushear cambios a la rama diego
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}  
      run: |
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }} diego
